name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - uses: https://code.unnecessary.tech/devries/gleam-test-action@v1
