name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: ghcr.io/gleam-lang/gleam:v1.13.0-erlang-alpine
    steps:
      - uses: actions/checkout@v4
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
